"""Round 57: Share Card — branded story-format lyric cards (v4 design).

A song-card button ("Share Card") renders a signature @MGLyricsbot image:
1080x1350 portrait (4:5), colorful dark template tinted with TWO colors pulled
from the album art (dominant + vibrant accent), lyric excerpt in bold centered
Manrope (Inter available), artist/title right under it, QR code floating light
on the left with an invisible dark halo for scan contrast, album artwork on
the right, and a "Generated by @MGLyricsbot" footer.

The QR deep-links to that exact song card in the bot
(t.me/MGLyricsbot?start=share_<token>).
"""
import colorsys
import hashlib
import io
import json
import logging
import os

import qrcode
import requests
from PIL import Image, ImageDraw, ImageFont, ImageFilter, ImageChops

from utils import atomic_json_write, is_section_marker_line

logger = logging.getLogger(__name__)

W, H = 1080, 1350
BOT_USERNAME = "MGLyricsbot"

_REPO_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_TOKEN_FILE = os.path.join(_REPO_DIR, "share_tokens.json")
_CARD_DIR = os.path.join(_REPO_DIR, "share_cards")
_FONT_DIR = os.path.join(_REPO_DIR, "assets", "fonts")

# Kind tags; _font() resolves them to the bundled family w/ DejaVu fallback.
_FONT_BOLD = "bold"
_FONT_REG = "regular"
_FONT_FAMILY = "manrope"  # or "inter"
_DEJAVU_BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
_DEJAVU_REG = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"


# ── Lyric excerpt ──────────────────────────────────────────────────────────

# Lines that are pure decoration from the lyrics source — never real lyrics.
# (Manrope has no glyph for these, so they rendered as tofu boxes.)
_DECORATIVE_CHARS = set("♪♫♬♩♭♮♯𝄞")


def _is_noise_line(line):
    s = (line or "").strip()
    if not s:
        return True
    if all(ch in _DECORATIVE_CHARS for ch in s):
        return True
    # Punctuation-only stubs ("...", "***", "~~~").
    if len(s) <= 3 and not any(ch.isalnum() for ch in s):
        return True
    return False


# Single-word filler openers worth skipping so the card opens on substance.
_FILLER_OPENERS = {
    "yeah", "oh", "uh", "uhh", "ah", "ooh", "aah", "hmm", "mm", "la",
    "hey", "yo", "ho",
}


def _strip_leading_filler(lines):
    if len(lines) >= 2:
        first = lines[0].strip().lower().rstrip(",.!?;:")
        if " " not in first and first in _FILLER_OPENERS:
            return lines[1:]
    return lines


def extract_excerpt(lyrics, max_lines=5):
    """Return up to `max_lines` lyric lines for the card.

    Preference: the [Chorus] section (the singable hook) -> the longest
    section -> the first lines. Section markers are never included.
    Decorative noise lines (♪ separators etc.) are dropped, and a
    leading one-word filler ("Yeah", "Oh", ...) is skipped so the card
    opens on a substantive line.
    """
    if not lyrics:
        return []
    # Split into (marker, lines) sections, dropping decorative noise.
    sections = []
    cur_marker, cur_lines = None, []
    for raw in lyrics.splitlines():
        line = raw.strip()
        if is_section_marker_line(line):
            if cur_lines or cur_marker is not None:
                sections.append((cur_marker, cur_lines))
            cur_marker, cur_lines = line, []
        elif line and not _is_noise_line(line):
            cur_lines.append(line)
    if cur_lines or cur_marker is not None:
        sections.append((cur_marker, cur_lines))

    def usable(lines):
        sel = [l for l in lines if l][:max_lines + 1]
        return _strip_leading_filler(sel)[:max_lines]

    # 1. Chorus first.
    for marker, lines in sections:
        if marker and "chorus" in marker.lower() and len(lines) >= 2:
            return usable(lines)
    # 2. Longest section.
    if sections:
        longest = max(sections, key=lambda s: len(s[1]))
        if len(longest[1]) >= 2:
            return usable(longest[1])
    # 3. First lines of the song.
    flat = [l for _, lines in sections for l in lines]
    return usable(flat)


# ── Share tokens (deep-link payloads) ──────────────────────────────────────

def get_share_token(artist, title):
    """Deterministic short token for an (artist, title) pair.

    Stored in share_tokens.json so /start share_<token> can reopen the exact
    song card. Deterministic => re-sharing the same song reuses the token and
    the cached card; the file only grows with newly shared songs.
    """
    artist = (artist or "").strip()
    title = (title or "").strip()
    key = f"{artist.lower()}|{title.lower()}"
    token = hashlib.sha1(key.encode("utf-8")).hexdigest()[:10]
    query = f"{artist} - {title}" if artist and title else (title or artist)
    try:
        with open(_TOKEN_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception:
        data = {}
    if token not in data:
        data[token] = query
        try:
            atomic_json_write(_TOKEN_FILE, data)
        except Exception as e:
            logger.debug(f"[sharecard] token persist failed: {e}")
    return token


def lookup_share_token(token):
    """Return the stored 'Artist - Title' query for a token, else None."""
    try:
        with open(_TOKEN_FILE, "r", encoding="utf-8") as f:
            return json.load(f).get(token)
    except Exception:
        return None


def build_share_link(token):
    return f"https://t.me/{BOT_USERNAME}?start=share_{token}"


def card_cache_path(token):
    os.makedirs(_CARD_DIR, exist_ok=True)
    return os.path.join(_CARD_DIR, f"{token}.png")


# ── Color ──────────────────────────────────────────────────────────────────

def dominant_color(img):
    """Most representative color of the artwork.

    Most-common color among mid-tone, reasonably saturated pixels; falls back
    to the average color. Never raises.
    """
    try:
        small = img.convert("RGB").resize((64, 64), Image.LANCZOS)
        colors = small.getcolors(64 * 64) or []
        colors.sort(key=lambda c: c[0], reverse=True)
        for _, (r, g, b) in colors:
            mx, mn = max(r, g, b), min(r, g, b)
            if 40 < (r + g + b) // 3 < 215 and (mx - mn) > 24:
                return (r, g, b)
        # Fallback: average.
        px = list(small.getdata())
        n = len(px)
        return tuple(sum(c[i] for c in px) // n for i in range(3))
    except Exception:
        return (90, 110, 200)


def vibrant_color(img):
    """Most saturated mid-light color of the artwork: the accent color.

    Falls back to the dominant color when the art is monochrome. Never
    raises.
    """
    try:
        small = img.convert("RGB").resize((64, 64), Image.LANCZOS)
        best, best_score = None, -1.0
        for r, g, b in small.getdata():
            mx, mn = max(r, g, b), min(r, g, b)
            if mx == 0:
                continue
            sat = (mx - mn) / mx
            light = (r + g + b) / 3 / 255.0
            if 0.22 < light < 0.88 and sat > 0.30:
                score = sat * (1.0 - abs(light - 0.55))
                if score > best_score:
                    best, best_score = (r, g, b), score
        return best if best is not None else dominant_color(img)
    except Exception:
        return (120, 140, 230)


def clamp_glow_color(rgb):
    """Clamp a glow tint so text contrast always holds on the dark template.

    - Perceptual-luminance cap (WCAG weights): neon covers get tamed instead
      of nuking readability.
    - HLS lightness pinned to [0.30, 0.55]: black art still glows, white art
      can't haze out.
    - Saturation lifted to 0.45 for chromatic colors; achromatic (gray)
      colors stay neutral instead of inventing a hue.
    """
    try:
        r, g, b = (x / 255.0 for x in rgb)
        lum = 0.2126 * r + 0.7152 * g + 0.0722 * b
        if lum > 0.5:
            f = 0.5 / lum
            r, g, b = r * f, g * f, b * f
        h, l, s = colorsys.rgb_to_hls(r, g, b)
        l = max(0.30, min(0.55, l))
        if s >= 0.15:
            s = max(s, 0.45)
        r, g, b = colorsys.hls_to_rgb(h, l, s)
        return (int(r * 255), int(g * 255), int(b * 255))
    except Exception:
        return (90, 110, 200)


def _mix(a, b, t):
    return tuple(int(a[i] + (b[i] - a[i]) * t) for i in range(3))


def accent_color(rgb):
    """Vivid accent derived from the artwork.

    Starts from the contrast-safe clamped color, then guarantees real
    saturation: monochrome covers (sepia, black-and-white) get a warm,
    rich tone from their own lightness instead of a muddy gray, so every
    card has a colorful vibe while staying in the artwork's tonal family.
    """
    try:
        r, g, b = clamp_glow_color(rgb)
        h, l, s = colorsys.rgb_to_hls(r / 255.0, g / 255.0, b / 255.0)
        if s < 0.35:
            if s < 0.05:
                h = 0.09  # pure gray -> warm gold
            s = 0.55
            l = max(0.35, min(0.55, l))
        r, g, b = colorsys.hls_to_rgb(h, l, s)
        return (int(r * 255), int(g * 255), int(b * 255))
    except Exception:
        return (230, 170, 80)


def fetch_artwork(url, timeout=10):
    """Download artwork -> PIL Image (RGB), or None. Never raises."""
    if not url:
        return None
    try:
        r = requests.get(url, timeout=timeout)
        r.raise_for_status()
        return Image.open(io.BytesIO(r.content)).convert("RGB")
    except Exception as e:
        logger.debug(f"[sharecard] artwork fetch failed: {e}")
        return None


# ── Rendering helpers ──────────────────────────────────────────────────────

def _glyph_font(size):
    """DejaVu for glyphs the bundled family lacks (e.g. the ♪ placeholder).

    Manrope/Inter have no musical-note glyphs; DejaVu does.
    """
    try:
        return ImageFont.truetype(_DEJAVU_REG, size)
    except Exception:
        return ImageFont.load_default()


def _font(kind, size):
    """Resolve a kind tag ('bold'/'regular') to the bundled font family.

    Falls back to DejaVu when the bundled TTF is missing, so the card
    always renders.
    """
    p = os.path.join(_FONT_DIR, f"{_FONT_FAMILY}-{kind}.ttf")
    if not os.path.exists(p):
        p = _DEJAVU_BOLD if kind == "bold" else _DEJAVU_REG
    try:
        return ImageFont.truetype(p, size)
    except Exception:
        return ImageFont.load_default()


def _text_size(draw, text, font):
    l, t, r, b = draw.textbbox((0, 0), text, font=font)
    return r - l, b - t


def _wrap(draw, text, font, max_w):
    words = text.split()
    lines, cur = [], ""
    for w in words:
        t = (cur + " " + w).strip()
        if _text_size(draw, t, font)[0] <= max_w or not cur:
            cur = t
        else:
            lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return lines or [""]


def _vgrad(w, h, top, bottom):
    base = Image.new("RGB", (1, h))
    for y in range(h):
        t = y / max(h - 1, 1)
        base.putpixel((0, y), tuple(int(a + (b - a) * t)
                                   for a, b in zip(top, bottom)))
    return base.resize((w, h))


def _radial_glow(size, rgb, peak_alpha=64):
    """Small radial glow, meant to be scaled up + blurred by the caller."""
    s = 160
    glow = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    px = glow.load()
    c = (s - 1) / 2
    for y in range(s):
        for x in range(s):
            d = (((x - c) ** 2 + (y - c) ** 2) ** 0.5) / c
            if d <= 1:
                px[x, y] = rgb + (int(peak_alpha * (1 - d) ** 2),)
    return glow.resize((size, size), Image.LANCZOS)


def _rounded(img, radius):
    mask = Image.new("L", img.size, 0)
    ImageDraw.Draw(mask).rounded_rectangle(
        [0, 0, img.size[0], img.size[1]], radius=radius, fill=255)
    out = img.convert("RGBA")
    out.putalpha(mask)
    return out


def _fit_excerpt(draw, lines, max_w, max_h):
    """Largest bold font (84 -> 40) such that wrapped lines fit max_w/max_h."""
    size = 84
    while size >= 40:
        font = _font(_FONT_BOLD, size)
        wrapped = []
        for ln in lines:
            wrapped.extend(_wrap(draw, ln, font, max_w))
        w = max((_text_size(draw, l, font)[0] for l in wrapped), default=0)
        h = len(wrapped) * int(size * 1.42)
        if w <= max_w and h <= max_h:
            return font, wrapped
        size -= 4
    font = _font(_FONT_BOLD, 40)
    wrapped = []
    for ln in lines:
        wrapped.extend(_wrap(draw, ln, font, max_w))
    return font, wrapped


def _ctext(draw, x, y, s, font, fill, shadow=True):
    """Horizontally-centered text with a soft drop shadow for pop."""
    if shadow:
        draw.text((x, y + 3), s, font=font, fill=(0, 0, 0, 170), anchor="ma")
    draw.text((x, y), s, font=font, fill=fill, anchor="ma")


# ── Card ───────────────────────────────────────────────────────────────────

def render_share_card(artist, title, excerpt_lines, artwork_img, deep_link):
    """Render the 1080x1350 share card. Returns PNG bytes. Never raises."""
    try:
        return _render(artist, title, excerpt_lines, artwork_img, deep_link)
    except Exception as e:
        logger.error(f"[sharecard] render failed: {e}", exc_info=True)
        # Last-resort: plain dark card with text, so the button never 500s.
        img = Image.new("RGB", (W, H), (10, 10, 14))
        d = ImageDraw.Draw(img)
        f = _font(_FONT_BOLD, 48)
        d.text((W // 2, H // 2), f"{artist} — {title}",
               font=f, fill=(240, 240, 245), anchor="mm")
        buf = io.BytesIO()
        img.save(buf, "PNG")
        return buf.getvalue()


# Tiny caption under the QR: a stranger's only question is "why scan?",
# so this whispers the payoff. Kept small and muted — never a shout.
QR_CAPTION = "Scan for lyrics & more"


def _build_qr_layer(matrix, box, radius=28):
    """White QR modules on a transparent layer, corners softly rounded.

    The rounding only ever clips the QR quiet zone, never data modules:
    the corner cut reaches r - r/sqrt(2) px deep, which must stay
    shallower than the quiet zone (border * box).
    """
    n = len(matrix)
    size = box * n
    layer = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    d = ImageDraw.Draw(layer)
    for r in range(n):
        for c in range(n):
            if matrix[r][c]:
                d.rectangle([c * box, r * box,
                             (c + 1) * box, (r + 1) * box],
                            fill=(246, 246, 250, 255))
    mask = Image.new("L", (size, size), 0)
    ImageDraw.Draw(mask).rounded_rectangle([0, 0, size, size],
                                           radius=radius, fill=255)
    layer.putalpha(ImageChops.multiply(layer.getchannel("A"), mask))
    return layer


def _render(artist, title, excerpt_lines, artwork_img, deep_link):
    if artwork_img is not None:
        dom_raw = dominant_color(artwork_img)
        vib_raw = vibrant_color(artwork_img)
    else:
        dom_raw, vib_raw = (90, 110, 200), (150, 120, 230)
    glow_rgb = clamp_glow_color(dom_raw)      # ambient wash (tamed)
    accent = accent_color(vib_raw)            # vivid accent (always colorful)

    # Base: dark vertical gradient tinted with the artwork's colors —
    # colorful, but deep enough that white type always pops.
    top = _mix(glow_rgb, (12, 12, 22), 0.72)
    bottom = _mix(accent, (7, 7, 13), 0.82)
    img = _vgrad(W, H, top, bottom).convert("RGBA")
    draw = ImageDraw.Draw(img)

    # Two ambient color glows: dominant behind the lyrics, vibrant low.
    glow1 = _radial_glow(1200, glow_rgb, peak_alpha=105).filter(
        ImageFilter.GaussianBlur(70))
    img.alpha_composite(glow1, (W // 2 - 600, 40))
    glow2 = _radial_glow(950, accent, peak_alpha=95).filter(
        ImageFilter.GaussianBlur(70))
    img.alpha_composite(glow2, (W // 2 - 475, 640))

    # Brand mark.
    brand = _font(_FONT_BOLD, 26)
    spaced = " ".join("LYRICS MASTER")
    _ctext(draw, W // 2, 100, spaced, brand, (126, 126, 140), shadow=False)

    # Excerpt, auto-fit into the central zone.
    font, wrapped = _fit_excerpt(draw, excerpt_lines, max_w=920, max_h=500)
    line_h = int(font.size * 1.42)
    total_h = len(wrapped) * line_h
    zone_top, zone_h = 240, 500
    y = zone_top + (zone_h - total_h) // 2
    for ln in wrapped:
        _ctext(draw, W // 2, y, ln, font, (245, 241, 234))
        y += line_h

    # Accent divider in the vibrant color.
    bar_w, bar_h, bar_y = 150, 9, zone_top + zone_h + 30
    draw.rounded_rectangle([W // 2 - bar_w // 2, bar_y,
                            W // 2 + bar_w // 2, bar_y + bar_h],
                           radius=bar_h // 2, fill=accent)

    # Artist — Title as two lines right under the excerpt, so the card is
    # self-explanatory wherever it travels.
    ay = bar_y + 46
    if artist:
        af = _font(_FONT_BOLD, 48)
        for ln in _wrap(draw, artist, af, 920)[:1]:
            _ctext(draw, W // 2, ay, ln, af, (247, 243, 237))
            ay += 62
    if title:
        tf = _font(_FONT_REG, 40)
        for ln in _wrap(draw, title, tf, 920)[:1]:
            _ctext(draw, W // 2, ay, ln, tf, (210, 204, 196))
            ay += 56

    # Bottom zone: QR code floating light on the left, album art anchoring
    # the right. No divider, no QR caption — whitespace keeps it clean.
    zone_y = 955

    # QR (left): white modules on their own layer, masked to soft rounded
    # corners that rhyme with the album art. A faint rounded container
    # sits behind it so it feels placed, not floating. The dark halo
    # underneath keeps scan contrast strong over any color glow.
    # (Corner rounding only ever clips the QR quiet zone, never modules.)
    qr = qrcode.QRCode(box_size=10, border=2)
    qr.add_data(deep_link)
    qr.make(fit=True)
    matrix = qr.get_matrix()  # includes the quiet-zone border
    n = len(matrix)
    box = max(2, 200 // n)
    size = box * n
    art_cy = zone_y + 150  # vertical center of the album art
    # The QR assembly (tile + caption) rides slightly above center so the
    # caption tucks just inside the artwork's bottom edge. A caption
    # dangling past the edge reads as a droop (near-alignment looks
    # accidental); tucked inside it reads as intentional.
    pad = 26
    caption_gap, caption_h = 12, 22
    art_bottom = zone_y + 300
    q_cx = 270
    q_cy = int(art_bottom - 10 - caption_h - caption_gap - pad - size / 2)
    qx0, qy0 = q_cx - size // 2, q_cy - size // 2
    halo = _radial_glow(400, (0, 0, 0), peak_alpha=120).filter(
        ImageFilter.GaussianBlur(55))
    img.alpha_composite(halo, (q_cx - 200, q_cy - 200))
    cont_layer = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    ImageDraw.Draw(cont_layer).rounded_rectangle(
        [qx0 - pad, qy0 - pad, qx0 + size + pad, qy0 + size + pad],
        radius=46, fill=(255, 255, 255, 16),
        outline=(255, 255, 255, 36), width=2)
    img.alpha_composite(cont_layer)
    qr_layer = _build_qr_layer(matrix, box)
    img.alpha_composite(qr_layer, (qx0, qy0))
    # Whisper-quiet caption beneath the QR: gives a stranger a reason
    # to scan, without disturbing the bottom zone's breathing room.
    cap = _font(_FONT_REG, 22)
    cb = draw.textbbox((0, 0), QR_CAPTION, font=cap)
    draw.text((q_cx - (cb[2] - cb[0]) / 2, qy0 + size + pad + caption_gap),
              QR_CAPTION, font=cap, fill=(135, 133, 145))

    # Album art (right) with a vibrant glow shadow behind it.
    if artwork_img is not None:
        art_sq = artwork_img.resize((300, 300), Image.LANCZOS)
    else:
        art_sq = Image.new("RGB", (300, 300), (22, 22, 32))
        d2 = ImageDraw.Draw(art_sq)
        nf = _glyph_font(130)  # ♪ missing from Manrope/Inter -> DejaVu
        nw, nh = _text_size(d2, "♪", nf)
        d2.text((150 - nw // 2, 150 - nh // 2 - 10), "♪", font=nf,
                fill=accent)
    art_glow = _radial_glow(500, accent, peak_alpha=120).filter(
        ImageFilter.GaussianBlur(45))
    ax, ay0 = 810 - 150, zone_y
    img.alpha_composite(art_glow, (810 - 250, ay0 - 90))
    img.alpha_composite(_rounded(art_sq, 40), (ax, ay0))

    # Footer: "Generated by @MGLyricsbot", handle in the accent color.
    foot = _font(_FONT_REG, 28)
    p1, p2 = "Generated by ", f"@{BOT_USERNAME}"
    w1, _ = _text_size(draw, p1, foot)
    w2, _ = _text_size(draw, p2, foot)
    fx = W // 2 - (w1 + w2) // 2
    fy = H - 56  # breathing room above: clear of the QR caption
    draw.text((fx, fy), p1, font=foot, fill=(135, 135, 150))
    draw.text((fx + w1, fy), p2, font=foot, fill=accent)

    out = img.convert("RGB")
    buf = io.BytesIO()
    out.save(buf, "PNG")
    return buf.getvalue()
