"""Round 57: Share Card — branded 1080x1920 story-format lyric cards (v2 design).

A song-card button ("Share Card") renders a signature @MGLyricsbot image:
1080x1920 portrait, colorful dark template tinted with TWO colors pulled from
the album art (dominant + vibrant accent), lyric excerpt in bold centered type
with the artist/title right under it, a bottom zone split by a vertical
divider (QR code on the left, album artwork on the right), and a
"Generated by @MGLyricsbot" footer.

The QR deep-links to that exact song card in the bot
(t.me/MGLyricsbot?start=share_<token>).
"""
import colorsys
import hashlib
import io
import json
import logging
import os

import qrcode
import requests
from PIL import Image, ImageDraw, ImageFont, ImageFilter

from utils import atomic_json_write, is_section_marker_line

logger = logging.getLogger(__name__)

W, H = 1080, 1920
BOT_USERNAME = "MGLyricsbot"

_REPO_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_TOKEN_FILE = os.path.join(_REPO_DIR, "share_tokens.json")
_CARD_DIR = os.path.join(_REPO_DIR, "share_cards")

_FONT_BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
_FONT_REG = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"


# ── Lyric excerpt ──────────────────────────────────────────────────────────

def extract_excerpt(lyrics, max_lines=5):
    """Return up to `max_lines` lyric lines for the card.

    Preference: the [Chorus] section (the singable hook) -> the longest
    section -> the first lines. Section markers are never included.
    """
    if not lyrics:
        return []
    # Split into (marker, lines) sections.
    sections = []
    cur_marker, cur_lines = None, []
    for raw in lyrics.splitlines():
        line = raw.strip()
        if is_section_marker_line(line):
            if cur_lines or cur_marker is not None:
                sections.append((cur_marker, cur_lines))
            cur_marker, cur_lines = line, []
        elif line:
            cur_lines.append(line)
    if cur_lines or cur_marker is not None:
        sections.append((cur_marker, cur_lines))

    def usable(lines):
        return [l for l in lines if l][:max_lines]

    # 1. Chorus first.
    for marker, lines in sections:
        if marker and "chorus" in marker.lower() and len(lines) >= 2:
            return usable(lines)
    # 2. Longest section.
    if sections:
        longest = max(sections, key=lambda s: len(s[1]))
        if len(longest[1]) >= 2:
            return usable(longest[1])
    # 3. First lines of the song.
    flat = [l for _, lines in sections for l in lines]
    return usable(flat)


# ── Share tokens (deep-link payloads) ──────────────────────────────────────

def get_share_token(artist, title):
    """Deterministic short token for an (artist, title) pair.

    Stored in share_tokens.json so /start share_<token> can reopen the exact
    song card. Deterministic => re-sharing the same song reuses the token and
    the cached card; the file only grows with newly shared songs.
    """
    artist = (artist or "").strip()
    title = (title or "").strip()
    key = f"{artist.lower()}|{title.lower()}"
    token = hashlib.sha1(key.encode("utf-8")).hexdigest()[:10]
    query = f"{artist} - {title}" if artist and title else (title or artist)
    try:
        with open(_TOKEN_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception:
        data = {}
    if token not in data:
        data[token] = query
        try:
            atomic_json_write(_TOKEN_FILE, data)
        except Exception as e:
            logger.debug(f"[sharecard] token persist failed: {e}")
    return token


def lookup_share_token(token):
    """Return the stored 'Artist - Title' query for a token, else None."""
    try:
        with open(_TOKEN_FILE, "r", encoding="utf-8") as f:
            return json.load(f).get(token)
    except Exception:
        return None


def build_share_link(token):
    return f"https://t.me/{BOT_USERNAME}?start=share_{token}"


def card_cache_path(token):
    os.makedirs(_CARD_DIR, exist_ok=True)
    return os.path.join(_CARD_DIR, f"{token}.png")


# ── Color ──────────────────────────────────────────────────────────────────

def dominant_color(img):
    """Most representative color of the artwork.

    Most-common color among mid-tone, reasonably saturated pixels; falls back
    to the average color. Never raises.
    """
    try:
        small = img.convert("RGB").resize((64, 64), Image.LANCZOS)
        colors = small.getcolors(64 * 64) or []
        colors.sort(key=lambda c: c[0], reverse=True)
        for _, (r, g, b) in colors:
            mx, mn = max(r, g, b), min(r, g, b)
            if 40 < (r + g + b) // 3 < 215 and (mx - mn) > 24:
                return (r, g, b)
        # Fallback: average.
        px = list(small.getdata())
        n = len(px)
        return tuple(sum(c[i] for c in px) // n for i in range(3))
    except Exception:
        return (90, 110, 200)


def vibrant_color(img):
    """Most saturated mid-light color of the artwork: the accent color.

    Falls back to the dominant color when the art is monochrome. Never
    raises.
    """
    try:
        small = img.convert("RGB").resize((64, 64), Image.LANCZOS)
        best, best_score = None, -1.0
        for r, g, b in small.getdata():
            mx, mn = max(r, g, b), min(r, g, b)
            if mx == 0:
                continue
            sat = (mx - mn) / mx
            light = (r + g + b) / 3 / 255.0
            if 0.22 < light < 0.88 and sat > 0.30:
                score = sat * (1.0 - abs(light - 0.55))
                if score > best_score:
                    best, best_score = (r, g, b), score
        return best if best is not None else dominant_color(img)
    except Exception:
        return (120, 140, 230)


def clamp_glow_color(rgb):
    """Clamp a glow tint so text contrast always holds on the dark template.

    - Perceptual-luminance cap (WCAG weights): neon covers get tamed instead
      of nuking readability.
    - HLS lightness pinned to [0.30, 0.55]: black art still glows, white art
      can't haze out.
    - Saturation lifted to 0.45 for chromatic colors; achromatic (gray)
      colors stay neutral instead of inventing a hue.
    """
    try:
        r, g, b = (x / 255.0 for x in rgb)
        lum = 0.2126 * r + 0.7152 * g + 0.0722 * b
        if lum > 0.5:
            f = 0.5 / lum
            r, g, b = r * f, g * f, b * f
        h, l, s = colorsys.rgb_to_hls(r, g, b)
        l = max(0.30, min(0.55, l))
        if s >= 0.15:
            s = max(s, 0.45)
        r, g, b = colorsys.hls_to_rgb(h, l, s)
        return (int(r * 255), int(g * 255), int(b * 255))
    except Exception:
        return (90, 110, 200)


def _mix(a, b, t):
    return tuple(int(a[i] + (b[i] - a[i]) * t) for i in range(3))


def accent_color(rgb):
    """Vivid accent derived from the artwork.

    Starts from the contrast-safe clamped color, then guarantees real
    saturation: monochrome covers (sepia, black-and-white) get a warm,
    rich tone from their own lightness instead of a muddy gray, so every
    card has a colorful vibe while staying in the artwork's tonal family.
    """
    try:
        r, g, b = clamp_glow_color(rgb)
        h, l, s = colorsys.rgb_to_hls(r / 255.0, g / 255.0, b / 255.0)
        if s < 0.35:
            if s < 0.05:
                h = 0.09  # pure gray -> warm gold
            s = 0.55
            l = max(0.35, min(0.55, l))
        r, g, b = colorsys.hls_to_rgb(h, l, s)
        return (int(r * 255), int(g * 255), int(b * 255))
    except Exception:
        return (230, 170, 80)


def fetch_artwork(url, timeout=10):
    """Download artwork -> PIL Image (RGB), or None. Never raises."""
    if not url:
        return None
    try:
        r = requests.get(url, timeout=timeout)
        r.raise_for_status()
        return Image.open(io.BytesIO(r.content)).convert("RGB")
    except Exception as e:
        logger.debug(f"[sharecard] artwork fetch failed: {e}")
        return None


# ── Rendering helpers ──────────────────────────────────────────────────────

def _font(path, size):
    try:
        return ImageFont.truetype(path, size)
    except Exception:
        return ImageFont.load_default()


def _text_size(draw, text, font):
    l, t, r, b = draw.textbbox((0, 0), text, font=font)
    return r - l, b - t


def _wrap(draw, text, font, max_w):
    words = text.split()
    lines, cur = [], ""
    for w in words:
        t = (cur + " " + w).strip()
        if _text_size(draw, t, font)[0] <= max_w or not cur:
            cur = t
        else:
            lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return lines or [""]


def _vgrad(w, h, top, bottom):
    base = Image.new("RGB", (1, h))
    for y in range(h):
        t = y / max(h - 1, 1)
        base.putpixel((0, y), tuple(int(a + (b - a) * t)
                                   for a, b in zip(top, bottom)))
    return base.resize((w, h))


def _radial_glow(size, rgb, peak_alpha=64):
    """Small radial glow, meant to be scaled up + blurred by the caller."""
    s = 160
    glow = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    px = glow.load()
    c = (s - 1) / 2
    for y in range(s):
        for x in range(s):
            d = (((x - c) ** 2 + (y - c) ** 2) ** 0.5) / c
            if d <= 1:
                px[x, y] = rgb + (int(peak_alpha * (1 - d) ** 2),)
    return glow.resize((size, size), Image.LANCZOS)


def _rounded(img, radius):
    mask = Image.new("L", img.size, 0)
    ImageDraw.Draw(mask).rounded_rectangle(
        [0, 0, img.size[0], img.size[1]], radius=radius, fill=255)
    out = img.convert("RGBA")
    out.putalpha(mask)
    return out


def _fit_excerpt(draw, lines, max_w, max_h):
    """Largest bold font (84 -> 40) such that wrapped lines fit max_w/max_h."""
    size = 84
    while size >= 40:
        font = _font(_FONT_BOLD, size)
        wrapped = []
        for ln in lines:
            wrapped.extend(_wrap(draw, ln, font, max_w))
        w = max((_text_size(draw, l, font)[0] for l in wrapped), default=0)
        h = len(wrapped) * int(size * 1.42)
        if w <= max_w and h <= max_h:
            return font, wrapped
        size -= 4
    font = _font(_FONT_BOLD, 40)
    wrapped = []
    for ln in lines:
        wrapped.extend(_wrap(draw, ln, font, max_w))
    return font, wrapped


def _ctext(draw, x, y, s, font, fill, shadow=True):
    """Horizontally-centered text with a soft drop shadow for pop."""
    if shadow:
        draw.text((x, y + 3), s, font=font, fill=(0, 0, 0, 170), anchor="ma")
    draw.text((x, y), s, font=font, fill=fill, anchor="ma")


# ── Card ───────────────────────────────────────────────────────────────────

def render_share_card(artist, title, excerpt_lines, artwork_img, deep_link):
    """Render the 1080x1920 share card. Returns PNG bytes. Never raises."""
    try:
        return _render(artist, title, excerpt_lines, artwork_img, deep_link)
    except Exception as e:
        logger.error(f"[sharecard] render failed: {e}", exc_info=True)
        # Last-resort: plain dark card with text, so the button never 500s.
        img = Image.new("RGB", (W, H), (10, 10, 14))
        d = ImageDraw.Draw(img)
        f = _font(_FONT_BOLD, 48)
        d.text((W // 2, H // 2), f"{artist} — {title}",
               font=f, fill=(240, 240, 245), anchor="mm")
        buf = io.BytesIO()
        img.save(buf, "PNG")
        return buf.getvalue()


def _render(artist, title, excerpt_lines, artwork_img, deep_link):
    if artwork_img is not None:
        dom_raw = dominant_color(artwork_img)
        vib_raw = vibrant_color(artwork_img)
    else:
        dom_raw, vib_raw = (90, 110, 200), (150, 120, 230)
    glow_rgb = clamp_glow_color(dom_raw)      # ambient wash (tamed)
    accent = accent_color(vib_raw)            # vivid accent (always colorful)

    # Base: dark vertical gradient tinted with the artwork's colors —
    # colorful, but deep enough that white type always pops.
    top = _mix(glow_rgb, (12, 12, 22), 0.72)
    bottom = _mix(accent, (7, 7, 13), 0.82)
    img = _vgrad(W, H, top, bottom).convert("RGBA")
    draw = ImageDraw.Draw(img)

    # Two ambient color glows: dominant behind the lyrics, vibrant low.
    glow1 = _radial_glow(1200, glow_rgb, peak_alpha=105).filter(
        ImageFilter.GaussianBlur(70))
    img.alpha_composite(glow1, (W // 2 - 600, 130))
    glow2 = _radial_glow(950, accent, peak_alpha=95).filter(
        ImageFilter.GaussianBlur(70))
    img.alpha_composite(glow2, (W // 2 - 475, 1050))

    # Brand mark (no emoji — DejaVu has no color-emoji glyphs).
    brand = _font(_FONT_BOLD, 30)
    spaced = " ".join("LYRICS MASTER")
    _ctext(draw, W // 2, 150, spaced, brand, (168, 168, 184), shadow=False)

    # Excerpt, auto-fit into the central zone.
    font, wrapped = _fit_excerpt(draw, excerpt_lines, max_w=920, max_h=660)
    line_h = int(font.size * 1.42)
    total_h = len(wrapped) * line_h
    zone_top, zone_h = 400, 660
    y = zone_top + (zone_h - total_h) // 2
    for ln in wrapped:
        _ctext(draw, W // 2, y, ln, font, (248, 248, 252))
        y += line_h

    # Accent divider in the vibrant color.
    bar_w, bar_h, bar_y = 150, 9, zone_top + zone_h + 30
    draw.rounded_rectangle([W // 2 - bar_w // 2, bar_y,
                            W // 2 + bar_w // 2, bar_y + bar_h],
                           radius=bar_h // 2, fill=accent)

    # Artist — Title as two lines right under the excerpt, so the card is
    # self-explanatory wherever it travels.
    ay = bar_y + 52
    if artist:
        af = _font(_FONT_BOLD, 50)
        for ln in _wrap(draw, artist, af, 920)[:1]:
            _ctext(draw, W // 2, ay, ln, af, (245, 245, 250))
            ay += 66
    if title:
        tf = _font(_FONT_REG, 42)
        for ln in _wrap(draw, title, tf, 920)[:1]:
            _ctext(draw, W // 2, ay, ln, tf, (205, 205, 218))
            ay += 58

    # Bottom zone (kept above y~1760 so story UIs don't cover it),
    # split by a vertical divider: QR left, album art right.
    zone_y = 1310
    divider_top, divider_bottom = zone_y + 10, zone_y + 430
    draw.line([W // 2, divider_top, W // 2, divider_bottom],
              fill=accent + (110,), width=3)

    # QR tile (left) with a vibrant border.
    qr = qrcode.QRCode(box_size=10, border=2)
    qr.add_data(deep_link)
    qr.make(fit=True)
    qimg = qr.make_image(fill_color="black",
                         back_color="white").convert("RGB")
    qimg = qimg.resize((292, 292), Image.NEAREST)
    tile = Image.new("RGB", (332, 332), (255, 255, 255))
    tile.paste(qimg, (20, 20))
    tile_r = _rounded(tile, 34)
    # Vibrant border: accent rounded-rect behind the white tile.
    border = Image.new("RGBA", (348, 348), (0, 0, 0, 0))
    ImageDraw.Draw(border).rounded_rectangle(
        [0, 0, 348, 348], radius=40, fill=accent + (255,))
    qx, qy = 270 - 174, zone_y + 20
    img.alpha_composite(border, (qx, qy))
    img.alpha_composite(tile_r, (qx + 8, qy + 8))

    cap = _font(_FONT_REG, 30)
    _ctext(draw, 270, qy + 372, "Scan to open this song", cap,
           (150, 150, 164), shadow=False)

    # Album art (right) with a vibrant glow shadow behind it.
    if artwork_img is not None:
        art_sq = artwork_img.resize((360, 360), Image.LANCZOS)
    else:
        art_sq = Image.new("RGB", (360, 360), (22, 22, 32))
        d2 = ImageDraw.Draw(art_sq)
        nf = _font(_FONT_REG, 160)
        nw, nh = _text_size(d2, "♪", nf)
        d2.text((180 - nw // 2, 180 - nh // 2 - 12), "♪", font=nf,
                fill=accent)
    art_glow = _radial_glow(560, accent, peak_alpha=120).filter(
        ImageFilter.GaussianBlur(45))
    ax, ay0 = 810 - 180, zone_y + 14
    img.alpha_composite(art_glow, (810 - 280, ay0 - 100))
    img.alpha_composite(_rounded(art_sq, 46), (ax, ay0))

    # Footer: "Generated by @MGLyricsbot", handle in the accent color.
    foot = _font(_FONT_REG, 32)
    p1, p2 = "Generated by ", f"@{BOT_USERNAME}"
    w1, _ = _text_size(draw, p1, foot)
    w2, _ = _text_size(draw, p2, foot)
    fx = W // 2 - (w1 + w2) // 2
    fy = H - 104
    draw.text((fx, fy), p1, font=foot, fill=(135, 135, 150))
    draw.text((fx + w1, fy), p2, font=foot, fill=accent)

    out = img.convert("RGB")
    buf = io.BytesIO()
    out.save(buf, "PNG")
    return buf.getvalue()
