#!/usr/bin/env python3
"""Mine Billboard Year-End Hot 100 (Wikipedia) into a local throwback pool.

One-time build step: scrapes the "Billboard Year-End Hot 100 singles of
YYYY" pages for 1980-2019, takes the top 70 per year, filters non-English
hits, dedupes across years (keeping the best rank), and writes
services/throwback_pool.py with THROWBACK_MINED = {'80s': [...], ...}.

Runtime stays fully local: no API, no key, no cost. Re-run to refresh.
Dev tool only — never imported by bot.py.
"""

import re
import sys
import time
import unicodedata
import urllib.request

YEARS = range(1980, 2020)
TOP_N = 70
UA = {"User-Agent": "LyricsMasterBot/1.0 (personal research tool)"}

# Non-English Billboard year-end hits 1980-2019 (normalized titles).
NON_ENGLISH = {
    "macarena", "despacito", "gangnam style", "la bamba",
    "99 luftballons", "rock me amadeus", "dragostea din tei",
    "numa numa", "ai se eu te pego", "bailando", "danza kuduro",
    "gasolina", "asereje", "ketchup song", "con calma", "mi gente",
    "taki taki", "vivir mi vida", "el perdon", "propuesta indecente",
}


def norm(s: str) -> str:
    s = unicodedata.normalize("NFKD", s or "")
    s = "".join(c for c in s if not unicodedata.combining(c))
    return re.sub(r"[^a-z0-9 ]", "", s.lower()).strip()


def clean_title(t: str) -> str:
    t = re.sub(r"\[[^\]]*\]", "", t or "").strip()
    if len(t) >= 2 and t[0] == t[-1] and t[0] in "\"'":
        t = t[1:-1].strip()
    return t


def fetch(year: int) -> str:
    url = ("https://en.wikipedia.org/wiki/"
           f"Billboard_Year-End_Hot_100_singles_of_{year}")
    req = urllib.request.Request(url, headers=UA)
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read().decode("utf-8", "replace")


def parse(html: str):
    m = re.search(r'<table class="wikitable.*?</table>', html, re.S)
    if not m:
        return []
    out = []
    for row in re.findall(r"<tr[^>]*>(.*?)</tr>", m.group(0), re.S)[1:]:
        cells = re.findall(r"<t[dh][^>]*>(.*?)</t[dh]>", row, re.S)
        cells = [re.sub(r"<[^>]+>", "", c).strip() for c in cells]
        if len(cells) < 3 or not cells[0].isdigit():
            continue
        out.append((int(cells[0]), clean_title(cells[1]), cells[2].strip()))
    return out


def main() -> None:
    best = {}  # (artist_norm, title_norm) -> dict
    for year in YEARS:
        try:
            rows = parse(fetch(year))[:TOP_N]
        except Exception as e:  # noqa: BLE001
            print(f"{year}: FETCH FAILED ({e})", file=sys.stderr)
            continue
        kept = 0
        for rank, title, artist in rows:
            if not title or not artist:
                continue
            nt = norm(title)
            if any(bad in nt for bad in NON_ENGLISH):
                continue
            if re.search(r"[^\x00-\x7f]", title):
                continue  # non-ASCII title: not English
            key = (norm(artist), nt)
            if key not in best or rank < best[key]["rank"]:
                best[key] = {"artist": artist, "song": title,
                             "year": year, "rank": rank}
                kept += 1
        print(f"{year}: {len(rows)} parsed, {kept} kept")
        time.sleep(0.5)

    pools = {"80s": [], "90s": [], "2000s": [], "2010s": []}
    for e in best.values():
        y = e["year"]
        decade = ("80s" if y < 1990 else "90s" if y < 2000
                  else "2000s" if y < 2010 else "2010s")
        pools[decade].append(e)
    for v in pools.values():
        v.sort(key=lambda e: (e["year"], e["rank"]))

    total = sum(len(v) for v in pools.values())
    print(f"total: {total} songs")

    lines = [
        '"""Billboard Year-End Hot 100 picks, 1980-2019 (top 70/year).',
        "",
        "Generated by tools/mine_throwback.py from Wikipedia. Each entry is",
        "a real charted song with its actual chart year and year-end rank,",
        "so decade labels need no verification. Fully local at runtime.",
        '"""',
        "",
        "THROWBACK_MINED = {",
    ]
    for decade, entries in pools.items():
        lines.append(f"    {decade!r}: [")
        for e in entries:
            lines.append(f"        {e!r},")
        lines.append("    ],")
    lines.append("}")
    lines.append("")
    with open("services/throwback_pool.py", "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("wrote services/throwback_pool.py")


if __name__ == "__main__":
    main()
